# Generated by Django 4.2 on 2023-05-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0002_item_order_orderitem_delete_employee_order_itams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='itams',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.amount'),
        ),
        migrations.AddField(
            model_name='item',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.coverage'),
        ),
        migrations.AddField(
            model_name='item',
            name='flavour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.flavours'),
        ),
        migrations.AddField(
            model_name='item',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.option'),
        ),
        migrations.AddField(
            model_name='item',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.toppings'),
        ),
    ]
