# Generated by Django 4.2 on 2023-05-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0003_amount_coverage_flavours_option_toppings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option',
        ),
        migrations.RemoveField(
            model_name='item',
            name='topping',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.ManyToManyField(default=0, to='Cupcakaya.amount'),
        ),
        migrations.AddField(
            model_name='item',
            name='coverage',
            field=models.ManyToManyField(null=True, to='Cupcakaya.coverage'),
        ),
        migrations.AddField(
            model_name='item',
            name='flavour',
            field=models.ManyToManyField(null=True, to='Cupcakaya.flavours'),
        ),
        migrations.AddField(
            model_name='item',
            name='option',
            field=models.ManyToManyField(null=True, to='Cupcakaya.option'),
        ),
        migrations.AddField(
            model_name='item',
            name='topping',
            field=models.ManyToManyField(null=True, to='Cupcakaya.toppings'),
        ),
    ]
