# Generated by Django 4.2 on 2023-05-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0005_alter_item_amount_alter_item_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.ManyToManyField(null=True, to='Cupcakaya.amount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='coverage',
            field=models.ManyToManyField(null=True, to='Cupcakaya.coverage'),
        ),
        migrations.AlterField(
            model_name='item',
            name='flavour',
            field=models.ManyToManyField(null=True, to='Cupcakaya.flavours'),
        ),
        migrations.AlterField(
            model_name='item',
            name='option',
            field=models.ManyToManyField(null=True, to='Cupcakaya.option'),
        ),
        migrations.AlterField(
            model_name='item',
            name='topping',
            field=models.ManyToManyField(null=True, to='Cupcakaya.toppings'),
        ),
    ]
