# Generated by Django 4.2 on 2023-05-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0006_item_category_alter_item_amount_alter_item_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
