# Generated by Django 4.2 on 2023-05-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0007_alter_amount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
