# Generated by Django 4.2 on 2023-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0012_flavours_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='category',
            field=models.CharField(choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='category',
            field=models.CharField(choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.CharField(choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='category',
            field=models.CharField(choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toppings',
            name='category',
            field=models.CharField(choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=100, null=True),
        ),
    ]
