# Generated by Django 4.2 on 2023-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0014_alter_item_amount_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='flavour',
        ),
        migrations.AddField(
            model_name='item',
            name='flavour',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
