# Generated by Django 4.2 on 2023-05-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0016_remove_item_flavour_item_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavours',
            name='idnum',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
