# Generated by Django 4.2 on 2023-05-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0017_flavours_idnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavours',
            name='idnum',
        ),
    ]
