# Generated by Django 4.2 on 2023-05-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0018_remove_flavours_idnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='flavour',
        ),
        migrations.AddField(
            model_name='item',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.flavours'),
        ),
    ]
