# Generated by Django 4.2 on 2023-05-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0020_flavours_flav_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='amo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='cov_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='opt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='shape_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toppings',
            name='top_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flavours',
            name='flav_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
