# Generated by Django 4.2 on 2023-05-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0021_amount_amo_id_coverage_cov_id_option_opt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option',
        ),
        migrations.RemoveField(
            model_name='item',
            name='topping',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.amount'),
        ),
        migrations.AddField(
            model_name='item',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.coverage'),
        ),
        migrations.AddField(
            model_name='item',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.option'),
        ),
        migrations.AddField(
            model_name='item',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.toppings'),
        ),
    ]
