# Generated by Django 4.2 on 2023-05-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0023_rename_cov_id_coverage_cove_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cupcakaya.shape'),
        ),
    ]
