# Generated by Django 4.2.1 on 2023-05-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0024_item_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Ck', 'Cake'), ('Cup', 'Cupcake'), ('Cp', 'Cakepop'), ('Co', 'Cookie')], max_length=15, null=True),
        ),
    ]
