# Generated by Django 4.2 on 2023-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0025_item_slug_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
