# Generated by Django 4.2 on 2023-05-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0033_alter_order_items_alter_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
