# Generated by Django 4.2 on 2023-05-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cupcakaya', '0034_remove_order_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
